-- SCHEMA

CREATE DATABASE burgers_db;
USE burgers_db;

CREATE TABLE burgers (
id INTEGER(10) NOT NULL AUTO_INCREMENT,
burger_name VARCHAR(20) NOT NULL,
devoured BOOLEAN DEFAULT true,
PRIMARY KEY (id)
);